version: "3"
services:
#  api:
#    depends_on:
#      - db
#    container_name: api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "8080:8080"
#    links:
#      - db

  db:
    container_name: db
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pgdb
    volumes:
      - /var/financial-case/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"